import { ScraperSourceResult } from '../types';

export async function scrapeCentralGovernment(): Promise<ScraperSourceResult> {
  return {
    sourceId: 'central-gov',
    sourceName: 'Central Government Portals (AIIMS, ESIC, RRB, DSSSB, JIPMER, PGIMER, NIMHANS)',
    sourceType: 'official',
    opportunities: [
      {
        externalRef: 'NORCET-2026',
        profession: 'nursing',
        opportunityType: 'exam',
        title: 'NORCET 2026 (Nursing Officer Recruitment Common Eligibility Test)',
        organisation: 'AIIMS New Delhi & Central Government Hospitals',
        role: 'nursing_officer',
        qualificationSummary: 'B.Sc. (Hons.) Nursing / B.Sc. Nursing / Post Basic / GNM with 2 yrs exp',
        experienceMinYears: 0,
        salaryMin: 531000,
        salaryMax: 1678000,
        salaryRaw: '7th CPC Pay Matrix Level 7 (Rs. 44,900 - 1,42,400)',
        vacancyCount: 2218,
        ageMin: 18,
        ageMax: 30,
        applicationStart: '2026-07-24',
        applicationDeadline: '2026-08-13',
        examDate: '2026-09-12',
        admitCardDate: '2026-09-09',
        status: 'open',
        officialNotificationUrl: 'https://www.aiimsexams.ac.in/advertisement/6a6350f7e5a81c4267f4ff04',
        applicationUrl: 'https://www.aiimsexams.ac.in',
        sourceUrl: 'https://www.aiimsexams.ac.in',
        sourceName: 'AIIMS Examination Section',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },
      {
        externalRef: 'AIIMS-DELHI-NO-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Nursing Officer (Group B)',
        organisation: 'AIIMS New Delhi',
        jobType: 'government',
        locationState: 'Delhi',
        locationCity: 'New Delhi (Ansari Nagar)',
        role: 'nursing_officer',
        qualificationSummary: 'B.Sc. (Hons.) Nursing / B.Sc. Nursing / Post Basic B.Sc.',
        experienceMinYears: 0,
        salaryMin: 531000,
        salaryMax: 1678000,
        salaryRaw: 'Level 7 Pay Matrix (Rs. 44,900 - 1,42,400)',
        vacancyCount: 450,
        ageMin: 18,
        ageMax: 30,
        applicationStart: '2026-08-01',
        applicationDeadline: '2026-09-18',
        status: 'open',
        officialNotificationUrl: 'https://www.aiimsexams.ac.in/pdf/AIIMS_ND_NO_Advt.pdf',
        applicationUrl: 'https://www.aiimsexams.ac.in',
        sourceUrl: 'https://www.aiims.edu',
        sourceName: 'All India Institute of Medical Sciences (AIIMS)',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },
      {
        externalRef: 'ESIC-NO-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'ESIC Nursing Officer Recruitment 2026',
        organisation: 'Employees State Insurance Corporation (ESIC)',
        jobType: 'government',
        locationState: 'Maharashtra',
        locationCity: 'Mumbai & Regional Model Hospitals',
        role: 'nursing_officer',
        qualificationSummary: 'B.Sc. Nursing or GNM with 1 yr clinical experience in 50-bed hospital',
        experienceMinYears: 0,
        salaryMin: 538000,
        salaryMax: 1550000,
        salaryRaw: 'Level 7 (Rs. 44,900 - 1,42,400)',
        vacancyCount: 523,
        ageMin: 18,
        ageMax: 30,
        applicationStart: '2026-08-05',
        applicationDeadline: '2026-09-20',
        status: 'open',
        officialNotificationUrl: 'https://www.esic.gov.in/recruitments',
        applicationUrl: 'https://upsconline.nic.in/ora/Detail.php?post_id=ESIC_NO_2026',
        sourceUrl: 'https://www.esic.gov.in',
        sourceName: 'Employees State Insurance Corporation',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },
      {
        externalRef: 'RRB-NURSE-2026',
        profession: 'nursing',
        opportunityType: 'exam',
        title: 'RRB Nursing Superintendent / Staff Nurse Examination 2026',
        organisation: 'Railway Recruitment Boards (Indian Railways)',
        role: 'staff_nurse',
        qualificationSummary: 'GNM 3 yrs course or B.Sc. Nursing with State / INC Registration',
        experienceMinYears: 0,
        salaryMin: 538000,
        salaryMax: 1550000,
        salaryRaw: '7th CPC Level 7 (Rs. 44,900 Initial Pay) + Railway Allowances',
        vacancyCount: 713,
        ageMin: 20,
        ageMax: 40,
        applicationStart: '2026-08-17',
        applicationDeadline: '2026-09-16',
        examDate: '2026-11-20',
        status: 'open',
        officialNotificationUrl: 'https://www.rrbchennai.gov.in/downloads/CEN_04_2026_Paramedical.pdf',
        applicationUrl: 'https://www.rrbapply.gov.in',
        sourceUrl: 'https://indianrailways.gov.in',
        sourceName: 'Railway Recruitment Control Board',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },
      {
        externalRef: 'DSSSB-NO-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'DSSSB Nursing Officer (Health & Family Welfare Department)',
        organisation: 'Delhi Subordinate Services Selection Board (DSSSB)',
        jobType: 'government',
        locationState: 'Delhi',
        locationCity: 'New Delhi (Govt of NCT of Delhi)',
        role: 'nursing_officer',
        qualificationSummary: 'B.Sc. Nursing / Post Basic B.Sc. or GNM + 1 yr exp + Delhi Nursing Council Registration',
        experienceMinYears: 0,
        salaryMin: 531000,
        salaryMax: 1678000,
        salaryRaw: 'Group B Pay Level 7 (Rs. 44,900 - 1,42,400)',
        vacancyCount: 1507,
        ageMin: 18,
        ageMax: 30,
        applicationStart: '2026-08-10',
        applicationDeadline: '2026-09-15',
        status: 'open',
        officialNotificationUrl: 'https://dsssb.delhi.gov.in/current-vacancies',
        applicationUrl: 'https://dsssbonline.nic.in',
        sourceUrl: 'https://dsssb.delhi.gov.in',
        sourceName: 'Delhi Subordinate Services Selection Board',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },
      {
        externalRef: 'JIPMER-NO-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'JIPMER Senior Nursing Officer / Nursing Officer Recruitment',
        organisation: 'Jawaharlal Institute of Postgraduate Medical Education & Research (JIPMER)',
        jobType: 'government',
        locationState: 'Puducherry',
        locationCity: 'Puducherry & Karaikal',
        role: 'nursing_officer',
        qualificationSummary: 'B.Sc. Nursing or GNM with 2 years clinical experience in min 50 bedded hospital',
        experienceMinYears: 0,
        salaryMin: 531000,
        salaryMax: 1678000,
        salaryRaw: 'Level 7 Pay Matrix (Rs. 44,900 - 1,42,400)',
        vacancyCount: 180,
        ageMin: 18,
        ageMax: 35,
        applicationStart: '2026-08-01',
        applicationDeadline: '2026-09-10',
        status: 'open',
        officialNotificationUrl: 'https://www.jipmer.edu.in/announcements/jobs',
        applicationUrl: 'https://www.jipmer.edu.in/online-application/nursing-officer-2026',
        sourceUrl: 'https://www.jipmer.edu.in',
        sourceName: 'JIPMER Autonomous Central Institute',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },
    ],
    requirements: [
      // NORCET Atomic Pathways
      {
        externalRef: 'NORCET-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'msc'],
        isMandatory: true,
        pathwayId: 'norcet_path_bsc',
        orGroup: 'norcet_path_bsc',
        rawText: 'B.Sc. (Hons.) Nursing / B.Sc. Nursing from an INC recognized Institute (No experience required)',
        simpleText: 'B.Sc. Nursing graduates qualify with zero experience (Path 1)',
        remedyText: 'Graduate with B.Sc. Nursing degree.',
      },
      {
        externalRef: 'NORCET-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['post_basic'],
        isMandatory: true,
        pathwayId: 'norcet_path_bsc',
        orGroup: 'norcet_path_bsc',
        rawText: 'B.Sc. (Post-Certificate) / Post-Basic B.Sc. Nursing from an INC recognized Institute',
        simpleText: 'Post Basic B.Sc. Nursing qualifies with zero experience (Path 1)',
        remedyText: 'Complete Post Basic B.Sc. Nursing.',
      },
      {
        externalRef: 'NORCET-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['gnm'],
        isMandatory: true,
        pathwayId: 'norcet_path_gnm',
        orGroup: 'norcet_path_gnm',
        rawText: 'Diploma in General Nursing and Midwifery (GNM) with two years experience in min 50 bedded hospital',
        simpleText: 'GNM diploma holders (Path 2)',
        remedyText: 'Complete GNM and complete 2 years of 50+ bed clinical hospital service.',
      },
      {
        externalRef: 'NORCET-2026',
        requirementKind: 'experience',
        operator: 'gte',
        valueNumeric: 2,
        isMandatory: true,
        pathwayId: 'norcet_path_gnm',
        orGroup: 'norcet_path_gnm',
        rawText: 'Two years experience in minimum 50 bedded hospital after GNM qualification',
        simpleText: '2 years of clinical hospital experience (applicable for GNM Path 2)',
        remedyText: 'Gain 2 years of clinical hospital service in a recognized facility.',
      },
      {
        externalRef: 'NORCET-2026',
        requirementKind: 'registration',
        operator: 'exists',
        isMandatory: true,
        rawText: 'Registered as Nurses & Midwife with State / Indian Nursing Council',
        simpleText: 'Valid registration with INC or State Nursing Council',
        remedyText: 'Register or renew your license with your State Nursing Council.',
      },
      {
        externalRef: 'NORCET-2026',
        requirementKind: 'age',
        operator: 'lte',
        valueNumeric: 30,
        isMandatory: true,
        rawText: 'Between 18 and 30 Years as on 13 August 2026 (relaxations applicable as per rules)',
        simpleText: 'Age must be 30 years or under on the closing date',
        remedyText: 'Check age relaxation categories in the official notification.',
      },

      // ESIC Requirements
      {
        externalRef: 'ESIC-NO-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'post_basic', 'msc', 'gnm'],
        isMandatory: true,
        rawText: 'B.Sc. Nursing or GNM with 1 year experience in minimum 50 bedded hospital',
        simpleText: 'B.Sc. Nursing or GNM degree',
        remedyText: 'Complete B.Sc. Nursing or GNM.',
      },
      {
        externalRef: 'ESIC-NO-2026',
        requirementKind: 'registration',
        operator: 'exists',
        isMandatory: true,
        rawText: 'Registered as a Nurse and Midwife with State Nursing Council',
        simpleText: 'State Nursing Council registration certificate',
        remedyText: 'Ensure your RN/RM registration is active.',
      },

      // RRB Requirements
      {
        externalRef: 'RRB-NURSE-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['gnm', 'bsc_nursing', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'Certificate as Registered Nurse and Midwife having passed 3 years course in General Nursing and Midwifery (GNM) or B.Sc. Nursing',
        simpleText: 'GNM diploma or B.Sc. Nursing degree',
        remedyText: 'Complete GNM or B.Sc. Nursing.',
      },
      {
        externalRef: 'RRB-NURSE-2026',
        requirementKind: 'age',
        operator: 'lte',
        valueNumeric: 40,
        isMandatory: true,
        rawText: '20 to 40 years as on prescribed reference date',
        simpleText: 'Maximum age limit of 40 years (Central Railway rules)',
        remedyText: 'Verify OBC/SC/ST age relaxation in CEN 04/2026.',
      },

      // DSSSB Requirements
      {
        externalRef: 'DSSSB-NO-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'post_basic', 'gnm'],
        isMandatory: true,
        rawText: 'B.Sc. Nursing / Post-Basic B.Sc. OR Diploma in GNM with 1 year experience in 50 bedded hospital',
        simpleText: 'B.Sc. Nursing or GNM with 1 year experience',
        remedyText: 'Complete B.Sc. Nursing or GNM.',
      },
      {
        externalRef: 'DSSSB-NO-2026',
        requirementKind: 'registration',
        operator: 'exists',
        isMandatory: true,
        rawText: 'Registered as Nurse and Midwife with Delhi Nursing Council',
        simpleText: 'Delhi Nursing Council (DNC) registration',
        remedyText: 'Transfer or register with Delhi Nursing Council.',
      },
    ],
  };
}
