import { ScraperSourceResult } from '../types';

export async function scrapePrivateHospitals(): Promise<ScraperSourceResult> {
  return {
    sourceId: 'private-hospitals',
    sourceName: 'NABH Super-Speciality Hospital Portals',
    sourceType: 'official',
    opportunities: [
      // 1. Manipal Hospital - Bangalore ICU
      {
        externalRef: 'MANIPAL-BLR-ICU-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Staff Nurse — Medical & Surgical ICU',
        organisation: 'Manipal Hospital',
        jobType: 'private',
        locationState: 'Karnataka',
        locationCity: 'Bangalore (Old Airport Road & Whitefield)',
        role: 'icu',
        qualificationSummary: 'B.Sc. Nursing or GNM with 2+ years ICU experience',
        experienceMinYears: 2,
        salaryMin: 360000,
        salaryMax: 480000,
        salaryRaw: 'Rs. 30,000 - 40,000 / month + Critical Care Shift Allowance',
        vacancyCount: 15,
        applicationStart: '2026-08-01',
        applicationDeadline: '2026-09-30',
        status: 'open',
        officialNotificationUrl: 'https://careers.manipalhospitals.com/manipalhospitals/jobslist?department=Nursing&location=Bangalore',
        applicationUrl: 'https://careers.manipalhospitals.com/manipalhospitals/jobslist?department=Nursing&location=Bangalore',
        sourceUrl: 'https://careers.manipalhospitals.com',
        sourceName: 'Manipal Hospitals Career Portal',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 2. Apollo Hospitals - Chennai OT
      {
        externalRef: 'APOLLO-CHN-OT-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Operation Theatre (OT) Staff Nurse',
        organisation: 'Apollo Hospitals',
        jobType: 'private',
        locationState: 'Tamil Nadu',
        locationCity: 'Chennai (Greams Road)',
        role: 'ot',
        qualificationSummary: 'B.Sc. Nursing or GNM with 1+ years OT experience',
        experienceMinYears: 1,
        salaryMin: 320000,
        salaryMax: 450000,
        salaryRaw: 'Rs. 26,000 - 38,000 / month',
        vacancyCount: 8,
        applicationStart: '2026-08-10',
        applicationDeadline: '2026-09-25',
        status: 'open',
        officialNotificationUrl: 'https://careers-myhr-apollo.peoplestrong.com/job/detail/APG_SN_1842843',
        applicationUrl: 'https://careers-myhr-apollo.peoplestrong.com/job/detail/APG_SN_1842843',
        sourceUrl: 'https://careers-myhr-apollo.peoplestrong.com/job/joblist',
        sourceName: 'Apollo Hospitals Candidate Portal (PeopleStrong)',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 3. Max Healthcare - Delhi Emergency
      {
        externalRef: 'MAX-DELHI-ER-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Emergency & Trauma Ward Staff Nurse',
        organisation: 'Max Healthcare',
        jobType: 'private',
        locationState: 'Delhi',
        locationCity: 'Saket & Patparganj, New Delhi',
        role: 'emergency',
        qualificationSummary: 'B.Sc. Nursing with BLS/ACLS and 1-3 years ER experience',
        experienceMinYears: 1,
        salaryMin: 380000,
        salaryMax: 520000,
        salaryRaw: 'Rs. 32,000 - 44,000 / month',
        vacancyCount: 10,
        applicationStart: '2026-08-15',
        applicationDeadline: '2026-10-10',
        status: 'open',
        officialNotificationUrl: 'https://www.maxhealthcare.in/careers/nursing-jobs-saket',
        applicationUrl: 'https://www.maxhealthcare.in/careers/nursing-jobs-saket',
        sourceUrl: 'https://www.maxhealthcare.in',
        sourceName: 'Max Healthcare Official Careers',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 4. Fortis Healthcare - Mumbai Cath Lab
      {
        externalRef: 'FORTIS-MUM-CATH-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Cath Lab & Cardiac Care Staff Nurse',
        organisation: 'Fortis Healthcare',
        jobType: 'private',
        locationState: 'Maharashtra',
        locationCity: 'Mumbai (Mulund & Kalyan)',
        role: 'cardiac_icu',
        qualificationSummary: 'B.Sc. Nursing or GNM with 2+ years Cardiac / Cath Lab experience',
        experienceMinYears: 2,
        salaryMin: 400000,
        salaryMax: 550000,
        salaryRaw: 'Rs. 34,000 - 46,000 / month',
        vacancyCount: 6,
        applicationStart: '2026-08-12',
        applicationDeadline: '2026-09-30',
        status: 'open',
        officialNotificationUrl: 'https://www.fortishealthcare.com/careers/nursing-mumbai',
        applicationUrl: 'https://www.fortishealthcare.com/careers/nursing-mumbai',
        sourceUrl: 'https://www.fortishealthcare.com',
        sourceName: 'Fortis Healthcare Careers',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 5. Narayana Health - Bangalore PICU
      {
        externalRef: 'NH-BLR-PICU-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Pediatric ICU (PICU) & NICU Staff Nurse',
        organisation: 'Narayana Health',
        jobType: 'private',
        locationState: 'Karnataka',
        locationCity: 'Bangalore (Narayana Health City, Bommasandra)',
        role: 'pediatric',
        qualificationSummary: 'B.Sc. Nursing / GNM with 1+ years pediatric or neonatal ICU experience',
        experienceMinYears: 1,
        salaryMin: 340000,
        salaryMax: 480000,
        salaryRaw: 'Rs. 28,000 - 40,000 / month',
        vacancyCount: 12,
        applicationStart: '2026-08-05',
        applicationDeadline: '2026-09-28',
        status: 'open',
        officialNotificationUrl: 'https://careers.narayanahealth.org/job-details/staff-nurse-picu-bangalore',
        applicationUrl: 'https://careers.narayanahealth.org/job-details/staff-nurse-picu-bangalore',
        sourceUrl: 'https://careers.narayanahealth.org',
        sourceName: 'Narayana Health Official Careers',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 6. Medanta - Gurugram Oncology
      {
        externalRef: 'MEDANTA-GUR-ONCO-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Staff Nurse — Medical Oncology & Day Care Chemotherapy',
        organisation: 'Medanta The Medicity',
        jobType: 'private',
        locationState: 'Haryana',
        locationCity: 'Gurugram (Sector 38)',
        role: 'oncology',
        qualificationSummary: 'B.Sc. Nursing with Chemotherapy administration certification & 1+ yr exp',
        experienceMinYears: 1,
        salaryMin: 380000,
        salaryMax: 500000,
        salaryRaw: 'Rs. 32,000 - 42,000 / month',
        vacancyCount: 8,
        applicationStart: '2026-08-10',
        applicationDeadline: '2026-10-05',
        status: 'open',
        officialNotificationUrl: 'https://www.medanta.org/careers/nursing-oncology-gurugram',
        applicationUrl: 'https://www.medanta.org/careers/nursing-oncology-gurugram',
        sourceUrl: 'https://www.medanta.org',
        sourceName: 'Medanta Hospital Official Careers',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 7. Apollo Hospitals - Hyderabad ICU
      {
        externalRef: 'APOLLO-HYD-ICU-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Staff Nurse — Neuro & Trauma ICU',
        organisation: 'Apollo Hospitals Jubilee Hills',
        jobType: 'private',
        locationState: 'Telangana',
        locationCity: 'Hyderabad',
        role: 'icu',
        qualificationSummary: 'B.Sc. Nursing or GNM with 2+ years Neuro ICU experience',
        experienceMinYears: 2,
        salaryMin: 360000,
        salaryMax: 480000,
        salaryRaw: 'Rs. 30,000 - 40,000 / month',
        vacancyCount: 12,
        applicationStart: '2026-08-14',
        applicationDeadline: '2026-10-05',
        status: 'open',
        officialNotificationUrl: 'https://careers-myhr-apollo.peoplestrong.com/job/detail/APG_SN_1839201',
        applicationUrl: 'https://careers-myhr-apollo.peoplestrong.com/job/detail/APG_SN_1839201',
        sourceUrl: 'https://careers-myhr-apollo.peoplestrong.com/job/joblist',
        sourceName: 'Apollo Hospitals Candidate Portal (PeopleStrong)',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 8. Manipal Hospital - Jaipur Staff Nurse
      {
        externalRef: 'MANIPAL-JAI-NURSE-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Staff Nurse — General Wards & Day Care',
        organisation: 'Manipal Hospital Jaipur',
        jobType: 'private',
        locationState: 'Rajasthan',
        locationCity: 'Jaipur (Vidhyadhar Nagar)',
        role: 'staff_nurse',
        qualificationSummary: 'GNM or B.Sc. Nursing with RNC registration',
        experienceMinYears: 0,
        salaryMin: 260000,
        salaryMax: 360000,
        salaryRaw: 'Rs. 22,000 - 30,000 / month',
        vacancyCount: 14,
        applicationStart: '2026-08-18',
        applicationDeadline: '2026-09-28',
        status: 'open',
        officialNotificationUrl: 'https://careers.manipalhospitals.com/manipalhospitals/jobslist?department=Nursing&location=Jaipur',
        applicationUrl: 'https://careers.manipalhospitals.com/manipalhospitals/jobslist?department=Nursing&location=Jaipur',
        sourceUrl: 'https://careers.manipalhospitals.com',
        sourceName: 'Manipal Hospital Careers',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 9. Fortis Hospital - Kolkata OT
      {
        externalRef: 'FORTIS-KOL-OT-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Surgical OT & Recovery Room Staff Nurse',
        organisation: 'Fortis Hospital Kolkata',
        jobType: 'private',
        locationState: 'West Bengal',
        locationCity: 'Kolkata (Anandapur)',
        role: 'ot',
        qualificationSummary: 'B.Sc. Nursing / GNM with 1+ years surgical OT experience',
        experienceMinYears: 1,
        salaryMin: 300000,
        salaryMax: 420000,
        salaryRaw: 'Rs. 25,000 - 35,000 / month',
        vacancyCount: 6,
        applicationStart: '2026-08-20',
        applicationDeadline: '2026-10-12',
        status: 'open',
        officialNotificationUrl: 'https://www.fortishealthcare.com/careers/nursing-kolkata',
        applicationUrl: 'https://www.fortishealthcare.com/careers/nursing-kolkata',
        sourceUrl: 'https://www.fortishealthcare.com',
        sourceName: 'Fortis Healthcare Portal',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 10. Apollo Hospitals - Bangalore Cardiac
      {
        externalRef: 'APOLLO-BLR-CARD-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Staff Nurse — Cardiac Catheterization Lab & CCU',
        organisation: 'Apollo Hospitals Bangalore',
        jobType: 'private',
        locationState: 'Karnataka',
        locationCity: 'Bangalore (Bannerghatta Road & Jayanagar)',
        role: 'cardiac_icu',
        qualificationSummary: 'B.Sc. Nursing or GNM with 2+ years CCU / Cath Lab experience',
        experienceMinYears: 2,
        salaryMin: 380000,
        salaryMax: 500000,
        salaryRaw: 'Rs. 32,000 - 42,000 / month',
        vacancyCount: 10,
        applicationStart: '2026-08-22',
        applicationDeadline: '2026-10-15',
        status: 'open',
        officialNotificationUrl: 'https://careers-myhr-apollo.peoplestrong.com/job/detail/APG_SN_1845112',
        applicationUrl: 'https://careers-myhr-apollo.peoplestrong.com/job/detail/APG_SN_1845112',
        sourceUrl: 'https://careers-myhr-apollo.peoplestrong.com/job/joblist',
        sourceName: 'Apollo Hospitals Candidate Portal (PeopleStrong)',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },
    ],
    requirements: [
      // Manipal BLR ICU
      {
        externalRef: 'MANIPAL-BLR-ICU-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'gnm', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'B.Sc. Nursing or GNM with active State Nursing Council registration',
        simpleText: 'B.Sc. Nursing or GNM diploma',
        remedyText: 'Complete B.Sc. Nursing or GNM.',
      },
      {
        externalRef: 'MANIPAL-BLR-ICU-2026',
        requirementKind: 'experience',
        operator: 'gte',
        valueNumeric: 2,
        isMandatory: true,
        rawText: 'Minimum 2 years clinical experience in Medical / Surgical ICU in a 100+ bed NABH hospital',
        simpleText: '2 years ICU experience',
        remedyText: 'Complete 2 years of ICU service in a multi-speciality hospital.',
      },

      // Apollo CHN OT
      {
        externalRef: 'APOLLO-CHN-OT-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'gnm', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'Degree in B.Sc. Nursing or Diploma in GNM with Tamil Nadu Nursing Council registration',
        simpleText: 'B.Sc. Nursing or GNM diploma',
        remedyText: 'Complete B.Sc. Nursing or GNM.',
      },
      {
        externalRef: 'APOLLO-CHN-OT-2026',
        requirementKind: 'experience',
        operator: 'gte',
        valueNumeric: 1,
        isMandatory: true,
        rawText: 'Minimum 1 year clinical experience in major surgical Operation Theatre & scrubbing techniques',
        simpleText: '1 year OT experience',
        remedyText: 'Gain 1 year OT experience.',
      },

      // Max Delhi ER
      {
        externalRef: 'MAX-DELHI-ER-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'B.Sc. Nursing with valid Delhi Nursing Council (DNC) registration',
        simpleText: 'B.Sc. Nursing degree',
        remedyText: 'Complete B.Sc. Nursing.',
      },
      {
        externalRef: 'MAX-DELHI-ER-2026',
        requirementKind: 'experience',
        operator: 'gte',
        valueNumeric: 1,
        isMandatory: true,
        rawText: 'Minimum 1 year experience in Emergency & Trauma triage with active BLS / ACLS certification',
        simpleText: '1 year Emergency / Trauma experience',
        remedyText: 'Complete 1 year emergency department service.',
      },

      // Fortis Mumbai
      {
        externalRef: 'FORTIS-MUM-CATH-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'gnm', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'B.Sc. Nursing or GNM with Maharashtra Nursing Council registration',
        simpleText: 'B.Sc. Nursing or GNM',
        remedyText: 'Complete B.Sc. Nursing or GNM.',
      },
      {
        externalRef: 'FORTIS-MUM-CATH-2026',
        requirementKind: 'experience',
        operator: 'gte',
        valueNumeric: 2,
        isMandatory: true,
        rawText: 'Minimum 2 years experience in Cardiac Catheterization Laboratory & CCU care',
        simpleText: '2 years Cath Lab / CCU experience',
        remedyText: 'Complete 2 years cardiology clinical service.',
      },

      // Apollo BLR Cardiac
      {
        externalRef: 'APOLLO-BLR-CARD-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'gnm', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'B.Sc. Nursing or GNM with Karnataka Nursing Council (KNC) registration',
        simpleText: 'B.Sc. Nursing or GNM',
        remedyText: 'Complete B.Sc. Nursing or GNM.',
      },
      {
        externalRef: 'APOLLO-BLR-CARD-2026',
        requirementKind: 'experience',
        operator: 'gte',
        valueNumeric: 2,
        isMandatory: true,
        rawText: 'Minimum 2 years experience in CCU / Cath Lab in a tertiary care hospital',
        simpleText: '2 years CCU experience',
        remedyText: 'Complete 2 years CCU service.',
      },

      // Narayana Health Bengaluru PICU
      {
        externalRef: 'NH-BLR-PICU-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'gnm', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'B.Sc. Nursing or GNM with active State Nursing Council registration',
        simpleText: 'B.Sc. Nursing or GNM diploma',
        remedyText: 'Complete B.Sc. Nursing or GNM.',
      },
      {
        externalRef: 'NH-BLR-PICU-2026',
        requirementKind: 'experience',
        operator: 'gte',
        valueNumeric: 1,
        isMandatory: true,
        rawText: 'Minimum 1 year clinical experience in Pediatric ICU or Neonatal ICU in NABH hospital',
        simpleText: '1 year PICU / NICU experience',
        remedyText: 'Complete 1 year pediatric critical care service.',
      },
      {
        externalRef: 'NH-BLR-PICU-2026',
        requirementKind: 'registration',
        operator: 'exists',
        isMandatory: true,
        rawText: 'Active Registration with Karnataka Nursing Council (KNC)',
        simpleText: 'Karnataka Nursing Council (KNC) registration',
        remedyText: 'Ensure active KNC registration.',
      },

      // Medanta Gurugram Oncology
      {
        externalRef: 'MEDANTA-GUR-ONCO-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'gnm', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'B.Sc. Nursing or GNM with valid State Nursing Council registration',
        simpleText: 'B.Sc. Nursing or GNM diploma',
        remedyText: 'Complete B.Sc. Nursing or GNM.',
      },
      {
        externalRef: 'MEDANTA-GUR-ONCO-2026',
        requirementKind: 'experience',
        operator: 'gte',
        valueNumeric: 2,
        isMandatory: true,
        rawText: 'Minimum 2 years experience in Medical / Surgical Oncology or Chemotherapy administration',
        simpleText: '2 years Oncology experience',
        remedyText: 'Complete 2 years oncology clinical service.',
      },

      // Apollo Hyderabad ICU
      {
        externalRef: 'APOLLO-HYD-ICU-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'gnm', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'B.Sc. Nursing or GNM with State Nursing Council registration',
        simpleText: 'B.Sc. Nursing or GNM diploma',
        remedyText: 'Complete B.Sc. Nursing or GNM.',
      },
      {
        externalRef: 'APOLLO-HYD-ICU-2026',
        requirementKind: 'experience',
        operator: 'gte',
        valueNumeric: 1,
        isMandatory: true,
        rawText: 'Minimum 1 year experience in Medical ICU / CCU in a multi-speciality tertiary care hospital',
        simpleText: '1 year Medical ICU experience',
        remedyText: 'Gain 1 year ICU clinical service.',
      },
      {
        externalRef: 'APOLLO-HYD-ICU-2026',
        requirementKind: 'registration',
        operator: 'exists',
        isMandatory: true,
        rawText: 'Registered with Telangana State Nursing Council or reciprocity transfer',
        simpleText: 'Telangana State Nursing Council registration',
        remedyText: 'Ensure active TS nursing registration.',
      },

      // Manipal Jaipur Inpatient Ward
      {
        externalRef: 'MANIPAL-JAI-NURSE-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'gnm', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'B.Sc. Nursing or GNM with Rajasthan Nursing Council registration',
        simpleText: 'B.Sc. Nursing or GNM diploma',
        remedyText: 'Complete B.Sc. Nursing or GNM.',
      },
      {
        externalRef: 'MANIPAL-JAI-NURSE-2026',
        requirementKind: 'experience',
        operator: 'gte',
        valueNumeric: 1,
        isMandatory: true,
        rawText: 'Minimum 1 year experience in Inpatient Ward / Surgical Post-Op care',
        simpleText: '1 year Inpatient experience',
        remedyText: 'Gain 1 year hospital ward experience.',
      },

      // Fortis Kolkata OT
      {
        externalRef: 'FORTIS-KOL-OT-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'gnm', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'B.Sc. Nursing or GNM with West Bengal Nursing Council registration',
        simpleText: 'B.Sc. Nursing or GNM diploma',
        remedyText: 'Complete B.Sc. Nursing or GNM.',
      },
      {
        externalRef: 'FORTIS-KOL-OT-2026',
        requirementKind: 'experience',
        operator: 'gte',
        valueNumeric: 2,
        isMandatory: true,
        rawText: 'Minimum 2 years experience in Operation Theatre scrubbing and sterile field management',
        simpleText: '2 years OT experience',
        remedyText: 'Complete 2 years OT clinical service.',
      },
    ],
  };
}
