import { ScraperSourceResult } from '../types';

export async function scrapeStateGovernments(): Promise<ScraperSourceResult> {
  return {
    sourceId: 'state-gov',
    sourceName: 'State PSCs, DHS & Medical Recruitment Boards',
    sourceType: 'official',
    opportunities: [
      // 1. Karnataka
      {
        externalRef: 'KAR-KPSC-NURSE-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Staff Nurse (Directorate of Health & Family Welfare Services)',
        organisation: 'Karnataka Public Service Commission (KPSC)',
        jobType: 'government',
        locationState: 'Karnataka',
        locationCity: 'Bangalore & District Hospitals',
        role: 'staff_nurse',
        qualificationSummary: 'B.Sc. Nursing / GNM from KNC recognized institution',
        experienceMinYears: 0,
        salaryMin: 400000,
        salaryMax: 780000,
        salaryRaw: 'Rs. 33,450 - 62,600 (Karnataka State Pay Scale)',
        vacancyCount: 840,
        ageMin: 18,
        ageMax: 35,
        applicationStart: '2026-08-12',
        applicationDeadline: '2026-09-24',
        status: 'open',
        officialNotificationUrl: 'https://kpsc.karnataka.gov.in/storage/pdf-files/Staff_Nurse_Advt_2026.pdf',
        applicationUrl: 'https://kpsc.karnataka.gov.in/online-application',
        sourceUrl: 'https://kpsc.karnataka.gov.in',
        sourceName: 'Karnataka Public Service Commission (KPSC)',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 2. Maharashtra
      {
        externalRef: 'MAHA-DHS-NURSE-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Staff Nurse (Arogya Seva Mandal)',
        organisation: 'Directorate of Health Services (DHS Maharashtra)',
        jobType: 'government',
        locationState: 'Maharashtra',
        locationCity: 'Pune, Nagpur, Mumbai & District Civil Hospitals',
        role: 'staff_nurse',
        qualificationSummary: 'B.Sc. Nursing or GNM with MNC registration',
        experienceMinYears: 0,
        salaryMin: 420000,
        salaryMax: 900000,
        salaryRaw: 'Pay Matrix Level S-10 (Rs. 35,400 - 1,12,400)',
        vacancyCount: 650,
        ageMin: 18,
        ageMax: 38,
        applicationStart: '2026-08-18',
        applicationDeadline: '2026-09-30',
        status: 'open',
        officialNotificationUrl: 'https://arogya.maharashtra.gov.in/pdf/Staff_Nurse_Recruitment_2026.pdf',
        applicationUrl: 'https://arogya.maharashtra.gov.in/apply-online',
        sourceUrl: 'https://arogya.maharashtra.gov.in',
        sourceName: 'Maharashtra Health Services (Arogya Vibhag)',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 3. Tamil Nadu
      {
        externalRef: 'TN-MRB-NURSE-2026',
        profession: 'nursing',
        opportunityType: 'exam',
        title: 'Nurses Recruitment Examination 2026',
        organisation: 'Medical Services Recruitment Board (TN MRB)',
        role: 'staff_nurse',
        qualificationSummary: 'Diploma in Nursing (GNM) or B.Sc. Nursing with TNC Registration',
        experienceMinYears: 0,
        salaryMin: 430000,
        salaryMax: 920000,
        salaryRaw: 'Pay Scale Level 10 (Rs. 35,900 - 1,13,500)',
        vacancyCount: 980,
        ageMin: 18,
        ageMax: 32,
        applicationStart: '2026-08-10',
        applicationDeadline: '2026-09-20',
        examDate: '2026-11-15',
        status: 'open',
        officialNotificationUrl: 'https://www.mrb.tn.gov.in/notifications/Notification_07_MRB_2026.pdf',
        applicationUrl: 'https://www.mrb.tn.gov.in/online-registration',
        sourceUrl: 'https://www.mrb.tn.gov.in',
        sourceName: 'Tamil Nadu Medical Services Recruitment Board (MRB)',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 4. Kerala
      {
        externalRef: 'KERALA-PSC-NURSE-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Staff Nurse Grade II (Health Services Department)',
        organisation: 'Kerala Public Service Commission (Kerala PSC)',
        jobType: 'government',
        locationState: 'Kerala',
        locationCity: 'Thiruvananthapuram, Kochi, Kozhikode & All Districts',
        role: 'staff_nurse',
        qualificationSummary: 'B.Sc. Nursing or GNM with KNMC Registration',
        experienceMinYears: 0,
        salaryMin: 470000,
        salaryMax: 980000,
        salaryRaw: 'Scale of Pay Rs. 39,300 - 83,000 (Kerala Revised Pay)',
        vacancyCount: 420,
        ageMin: 20,
        ageMax: 36,
        applicationStart: '2026-08-01',
        applicationDeadline: '2026-09-15',
        status: 'open',
        officialNotificationUrl: 'https://www.keralapsc.gov.in/extra-ordinary-gazette-date-2026',
        applicationUrl: 'https://thulasi.psc.kerala.gov.in/thulasi/',
        sourceUrl: 'https://www.keralapsc.gov.in',
        sourceName: 'Kerala Public Service Commission (Thulasi Portal)',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 5. Uttar Pradesh
      {
        externalRef: 'UP-UPUMS-NURSE-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Nursing Officer (Computer Based Examination 2026)',
        organisation: 'UPUMS Saifai & UP State Medical Colleges',
        jobType: 'government',
        locationState: 'Uttar Pradesh',
        locationCity: 'Saifai (Etawah), Lucknow & Kanpur',
        role: 'nursing_officer',
        qualificationSummary: 'B.Sc. Nursing / Post Basic B.Sc. OR GNM with 2 yrs exp in min 50 bedded hospital',
        experienceMinYears: 0,
        salaryMin: 531000,
        salaryMax: 1678000,
        salaryRaw: 'Pay Matrix Level 7 (Rs. 44,900 - 1,42,400)',
        vacancyCount: 535,
        ageMin: 18,
        ageMax: 40,
        applicationStart: '2026-08-15',
        applicationDeadline: '2026-09-22',
        status: 'open',
        officialNotificationUrl: 'https://www.upums.ac.in/pdf/Advt_Nursing_Officer_2026.pdf',
        applicationUrl: 'https://www.upums.ac.in/apply-online',
        sourceUrl: 'https://www.upums.ac.in',
        sourceName: 'Uttar Pradesh University of Medical Sciences',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 6. Rajasthan
      {
        externalRef: 'RAJ-RSSB-NURSE-2026',
        profession: 'nursing',
        opportunityType: 'exam',
        title: 'Rajasthan Staff Nurse (GNM) Direct Recruitment Exam 2026',
        organisation: 'Rajasthan Staff Selection Board (RSMSSB)',
        role: 'staff_nurse',
        qualificationSummary: 'GNM Course or equivalent with RNC (Rajasthan Nursing Council) Registration',
        experienceMinYears: 0,
        salaryMin: 390000,
        salaryMax: 840000,
        salaryRaw: 'Pay Matrix Level L-11 (Rs. 37,800 - 1,19,700)',
        vacancyCount: 1588,
        ageMin: 21,
        ageMax: 40,
        applicationStart: '2026-08-08',
        applicationDeadline: '2026-09-18',
        examDate: '2026-11-08',
        status: 'open',
        officialNotificationUrl: 'https://rsmssb.rajasthan.gov.in/Static/files/Advt_GNM_Nurse_2026.pdf',
        applicationUrl: 'https://sso.rajasthan.gov.in/',
        sourceUrl: 'https://rsmssb.rajasthan.gov.in',
        sourceName: 'Rajasthan Staff Selection Board (RSSB)',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 7. West Bengal
      {
        externalRef: 'WB-WBHRB-NURSE-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Staff Nurse Grade II (Basic B.Sc. & GNM Cadre)',
        organisation: 'West Bengal Health Recruitment Board (WBHRB)',
        jobType: 'government',
        locationState: 'West Bengal',
        locationCity: 'Kolkata & District Hospital Sub-Divisions',
        role: 'staff_nurse',
        qualificationSummary: 'GNM or Basic B.Sc. Nursing or Post Basic with WBNC Registration & Bengali fluency',
        experienceMinYears: 0,
        salaryMin: 380000,
        salaryMax: 820000,
        salaryRaw: 'Pay Matrix Level 9 (Rs. 28,900 - 74,500) + WB State DA/HRA',
        vacancyCount: 2100,
        ageMin: 18,
        ageMax: 39,
        applicationStart: '2026-08-14',
        applicationDeadline: '2026-09-26',
        status: 'open',
        officialNotificationUrl: 'https://wbhrb.in/advertisement/Staff_Nurse_Gr_II_2026.pdf',
        applicationUrl: 'https://wbhrb.in/online-application',
        sourceUrl: 'https://wbhrb.in',
        sourceName: 'West Bengal Health Recruitment Board',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 8. Bihar
      {
        externalRef: 'BIHAR-BTSC-NURSE-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Staff Nurse Grade A (Bihar Health Subordinate Cadre)',
        organisation: 'Bihar Technical Service Commission (BTSC)',
        jobType: 'government',
        locationState: 'Bihar',
        locationCity: 'Patna, Gaya, Muzaffarpur & District Sub-Divisions',
        role: 'staff_nurse',
        qualificationSummary: 'GNM Training Certificate / B.Sc. Nursing with BNRC (Bihar Nursing Registration Council)',
        experienceMinYears: 0,
        salaryMin: 531000,
        salaryMax: 1678000,
        salaryRaw: 'Pay Level 7 (Rs. 44,900 - 1,42,400 Grade Pay Rs. 4600)',
        vacancyCount: 10709,
        ageMin: 21,
        ageMax: 37,
        applicationStart: '2026-08-01',
        applicationDeadline: '2026-09-12',
        status: 'open',
        officialNotificationUrl: 'https://btsc.bihar.gov.in/pdf/Staff_Nurse_Gr_A_Notice_2026.pdf',
        applicationUrl: 'https://btsc.bihar.gov.in/online-apply',
        sourceUrl: 'https://btsc.bihar.gov.in',
        sourceName: 'Bihar Technical Service Commission',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 9. Telangana
      {
        externalRef: 'TS-MHSRB-NURSE-2026',
        profession: 'nursing',
        opportunityType: 'exam',
        title: 'Staff Nurse Recruitment Examination 2026',
        organisation: 'Medical Health Services Recruitment Board (MHSRB Telangana)',
        role: 'staff_nurse',
        qualificationSummary: 'GNM or B.Sc. Nursing with Telangana State Nursing Council Registration',
        experienceMinYears: 0,
        salaryMin: 450000,
        salaryMax: 960000,
        salaryRaw: 'Scale of Pay Rs. 36,750 - 89,200 (TS Revised Pay Scales)',
        vacancyCount: 1240,
        ageMin: 18,
        ageMax: 44,
        applicationStart: '2026-08-16',
        applicationDeadline: '2026-09-28',
        examDate: '2026-11-22',
        status: 'open',
        officialNotificationUrl: 'https://mhsrb.telangana.gov.in/docs/Staff_Nurse_Advt_03_2026.pdf',
        applicationUrl: 'https://mhsrb.telangana.gov.in/online-application',
        sourceUrl: 'https://mhsrb.telangana.gov.in',
        sourceName: 'Medical Health Services Recruitment Board (Telangana)',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 10. Odisha
      {
        externalRef: 'ODISHA-OSSSC-NURSE-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Nursing Officer (District Cadre Group C)',
        organisation: 'Odisha Sub-ordinate Staff Selection Commission (OSSSC)',
        jobType: 'government',
        locationState: 'Odisha',
        locationCity: 'Bhubaneswar, Cuttack & District Headquarters',
        role: 'nursing_officer',
        qualificationSummary: 'B.Sc. Nursing or GNM with ONMRC Registration & Odia language proficiency',
        experienceMinYears: 0,
        salaryMin: 360000,
        salaryMax: 780000,
        salaryRaw: 'Pay Scale Level 8 (Rs. 29,200 - 92,300)',
        vacancyCount: 7483,
        ageMin: 21,
        ageMax: 38,
        applicationStart: '2026-08-10',
        applicationDeadline: '2026-09-25',
        status: 'open',
        officialNotificationUrl: 'https://www.osssc.gov.in/Public/Pages/Notice_Nursing_Officer_2026.pdf',
        applicationUrl: 'https://www.osssc.gov.in/Public/Pages/ApplyOnline.aspx',
        sourceUrl: 'https://www.osssc.gov.in',
        sourceName: 'Odisha Sub-ordinate Staff Selection Commission',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 11. Gujarat
      {
        externalRef: 'GUJ-GMC-NURSE-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Staff Nurse Class III (Commissioner of Health & Medical Education)',
        organisation: 'Gujarat Medical Services / OJAS Gujarat',
        jobType: 'government',
        locationState: 'Gujarat',
        locationCity: 'Ahmedabad, Vadodara, Surat & Civil Hospitals',
        role: 'staff_nurse',
        qualificationSummary: 'Basic B.Sc. Nursing or GNM with Gujarat Nursing Council (GNC) Registration',
        experienceMinYears: 0,
        salaryMin: 380000,
        salaryMax: 820000,
        salaryRaw: 'Fixed Pay Rs. 26,000 for 5 years, then Level 5 Regular Matrix',
        vacancyCount: 1120,
        ageMin: 20,
        ageMax: 35,
        applicationStart: '2026-08-12',
        applicationDeadline: '2026-09-20',
        status: 'open',
        officialNotificationUrl: 'https://ojas.gujarat.gov.in/AdvtDetailFiles/GMC_Staff_Nurse_2026.pdf',
        applicationUrl: 'https://ojas.gujarat.gov.in/AdvtList.aspx?type=lCxEnhanced',
        sourceUrl: 'https://ojas.gujarat.gov.in',
        sourceName: 'OJAS Gujarat Online Job Application System',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },

      // 12. Madhya Pradesh
      {
        externalRef: 'MP-NHM-NURSE-2026',
        profession: 'nursing',
        opportunityType: 'job',
        title: 'Staff Nurse (Female & Male) Contractual Vacancies',
        organisation: 'National Health Mission Madhya Pradesh (MP NHM)',
        jobType: 'government',
        locationState: 'Madhya Pradesh',
        locationCity: 'Bhopal, Indore, Jabalpur & Gwalior',
        role: 'staff_nurse',
        qualificationSummary: 'B.Sc. Nursing or GNM with MP Nursing Registration Council (MPNRC)',
        experienceMinYears: 0,
        salaryMin: 300000,
        salaryMax: 420000,
        salaryRaw: 'Honorarium Rs. 20,000 / month (Contractual)',
        vacancyCount: 960,
        ageMin: 21,
        ageMax: 43,
        applicationStart: '2026-08-15',
        applicationDeadline: '2026-09-25',
        status: 'open',
        officialNotificationUrl: 'https://www.mponline.gov.in/Quick%20Links/NHM/Doc/Staff_Nurse_Advt_2026.pdf',
        applicationUrl: 'https://www.mponline.gov.in',
        sourceUrl: 'https://www.mponline.gov.in',
        sourceName: 'NHM Madhya Pradesh Official Portal (MPOnline)',
        sourceType: 'official',
        lastVerifiedAt: '2026-08-28',
      },
    ],
    requirements: [
      // Karnataka
      {
        externalRef: 'KAR-KPSC-NURSE-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'gnm', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'Passed B.Sc. Nursing or GNM Course from an institution recognized by Government of Karnataka',
        simpleText: 'B.Sc. Nursing or GNM diploma',
        remedyText: 'Complete B.Sc. Nursing or GNM.',
      },
      {
        externalRef: 'KAR-KPSC-NURSE-2026',
        requirementKind: 'registration',
        operator: 'exists',
        isMandatory: true,
        rawText: 'Registered with Karnataka Nursing Council (KNC) as Nurse and Midwife',
        simpleText: 'Karnataka Nursing Council (KNC) registration',
        remedyText: 'Register or obtain reciprocity transfer with Karnataka Nursing Council.',
      },

      // Maharashtra
      {
        externalRef: 'MAHA-DHS-NURSE-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'gnm', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'Must possess B.Sc. Nursing degree or GNM diploma',
        simpleText: 'B.Sc. Nursing or GNM diploma',
        remedyText: 'Complete B.Sc. Nursing or GNM.',
      },
      {
        externalRef: 'MAHA-DHS-NURSE-2026',
        requirementKind: 'registration',
        operator: 'exists',
        isMandatory: true,
        rawText: 'Must be registered with Maharashtra Nursing Council (MNC)',
        simpleText: 'Maharashtra Nursing Council (MNC) registration',
        remedyText: 'Ensure your active registration with Maharashtra Nursing Council.',
      },

      // Tamil Nadu
      {
        externalRef: 'TN-MRB-NURSE-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['gnm', 'bsc_nursing', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'Successful completion of Diploma in General Nursing and Midwifery or Degree in B.Sc. Nursing',
        simpleText: 'GNM Diploma or B.Sc. Nursing',
        remedyText: 'Complete GNM or B.Sc. Nursing.',
      },
      {
        externalRef: 'TN-MRB-NURSE-2026',
        requirementKind: 'registration',
        operator: 'exists',
        isMandatory: true,
        rawText: 'Must be registered with the Tamil Nadu Nurses and Midwives Council (TNC)',
        simpleText: 'Tamil Nadu Nurses and Midwives Council registration',
        remedyText: 'Register with Tamil Nadu Nurses and Midwives Council (TNC).',
      },

      // Kerala
      {
        externalRef: 'KERALA-PSC-NURSE-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'gnm', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'A pass in Plus Two with General Nursing & Midwifery or B.Sc. Nursing',
        simpleText: 'B.Sc. Nursing or GNM diploma',
        remedyText: 'Complete GNM or B.Sc. Nursing.',
      },
      {
        externalRef: 'KERALA-PSC-NURSE-2026',
        requirementKind: 'registration',
        operator: 'exists',
        isMandatory: true,
        rawText: 'Certificate of Registration with the Kerala Nurses and Midwives Council (KNMC)',
        simpleText: 'Kerala Nurses and Midwives Council (KNMC) registration',
        remedyText: 'Register or renew your license with KNMC.',
      },

      // UPUMS Saifai
      {
        externalRef: 'UP-UPUMS-NURSE-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'post_basic', 'msc'],
        isMandatory: true,
        pathwayId: 'upums_path_bsc',
        orGroup: 'upums_path_bsc',
        rawText: 'B.Sc. (Hons.) Nursing / B.Sc. Nursing / Post Basic B.Sc. from INC recognized Institute (0 exp)',
        simpleText: 'B.Sc. Nursing / Post Basic (0 exp required)',
        remedyText: 'Complete B.Sc. Nursing.',
      },
      {
        externalRef: 'UP-UPUMS-NURSE-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['gnm'],
        isMandatory: true,
        pathwayId: 'upums_path_gnm',
        orGroup: 'upums_path_gnm',
        rawText: 'Diploma in GNM with 2 years experience in minimum 50 bedded hospital',
        simpleText: 'GNM Diploma (Path 2)',
        remedyText: 'Complete GNM diploma.',
      },
      {
        externalRef: 'UP-UPUMS-NURSE-2026',
        requirementKind: 'experience',
        operator: 'gte',
        valueNumeric: 2,
        isMandatory: true,
        pathwayId: 'upums_path_gnm',
        orGroup: 'upums_path_gnm',
        rawText: 'Two years experience in min 50 bedded hospital for GNM candidates',
        simpleText: '2 years hospital experience (for GNM)',
        remedyText: 'Complete 2 years of hospital service.',
      },

      // Rajasthan
      {
        externalRef: 'RAJ-RSSB-NURSE-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['gnm', 'bsc_nursing', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'GNM course or its equivalent qualification from an institute recognized by State Govt',
        simpleText: 'GNM or B.Sc. Nursing',
        remedyText: 'Complete GNM or B.Sc. Nursing.',
      },
      {
        externalRef: 'RAJ-RSSB-NURSE-2026',
        requirementKind: 'registration',
        operator: 'exists',
        isMandatory: true,
        rawText: "Registration in Rajasthan Nursing Council (RNC) as 'B' Grade Nurse",
        simpleText: 'Rajasthan Nursing Council (RNC) registration',
        remedyText: 'Register or obtain registration with RNC Jaipur.',
      },

      // West Bengal
      {
        externalRef: 'WB-WBHRB-NURSE-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['gnm', 'bsc_nursing', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'General Nursing and Midwifery (GNM) / Basic B.Sc. Nursing / Post Basic B.Sc. from WBNC recognized institution',
        simpleText: 'GNM or Basic B.Sc. Nursing degree',
        remedyText: 'Complete GNM or B.Sc. Nursing.',
      },
      {
        externalRef: 'WB-WBHRB-NURSE-2026',
        requirementKind: 'registration',
        operator: 'exists',
        isMandatory: true,
        rawText: 'Registration Certificate from West Bengal Nursing Council (WBNC)',
        simpleText: 'West Bengal Nursing Council (WBNC) registration',
        remedyText: 'Obtain reciprocal registration with West Bengal Nursing Council.',
      },

      // Bihar
      {
        externalRef: 'BIHAR-BTSC-NURSE-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['gnm', 'bsc_nursing', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'GNM Training Certificate / B.Sc. Nursing from Indian Nursing Council recognized college',
        simpleText: 'GNM Diploma or B.Sc. Nursing',
        remedyText: 'Complete GNM or B.Sc. Nursing.',
      },
      {
        externalRef: 'BIHAR-BTSC-NURSE-2026',
        requirementKind: 'registration',
        operator: 'exists',
        isMandatory: true,
        rawText: 'Registration with Bihar Nurses Registration Council (BNRC Patna)',
        simpleText: 'Bihar Nurses Registration Council (BNRC) registration',
        remedyText: 'Register with BNRC Patna.',
      },

      // Telangana
      {
        externalRef: 'TS-MHSRB-NURSE-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['gnm', 'bsc_nursing', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'Must possess General Nursing and Midwifery (GNM) or B.Sc. Nursing',
        simpleText: 'GNM or B.Sc. Nursing degree',
        remedyText: 'Complete GNM or B.Sc. Nursing.',
      },
      {
        externalRef: 'TS-MHSRB-NURSE-2026',
        requirementKind: 'registration',
        operator: 'exists',
        isMandatory: true,
        rawText: 'Must be registered with Telangana State Nursing and Midwives Council',
        simpleText: 'Telangana State Nursing Council registration',
        remedyText: 'Register with Telangana State Nursing Council.',
      },

      // Odisha
      {
        externalRef: 'ODISHA-OSSSC-NURSE-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['gnm', 'bsc_nursing', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'Passed GNM or B.Sc. Nursing from an INC recognized institution',
        simpleText: 'GNM or B.Sc. Nursing degree',
        remedyText: 'Complete GNM or B.Sc. Nursing.',
      },
      {
        externalRef: 'ODISHA-OSSSC-NURSE-2026',
        requirementKind: 'registration',
        operator: 'exists',
        isMandatory: true,
        rawText: 'Must be registered with the Odisha Nursing and Midwives Council (ONMRC)',
        simpleText: 'Odisha Nursing and Midwives Council (ONMRC) registration',
        remedyText: 'Register with ONMRC Bhubaneswar.',
      },

      // Gujarat
      {
        externalRef: 'GUJ-GMC-NURSE-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'gnm', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'Degree of B.Sc. (Nursing) or Diploma in General Nursing and Midwifery',
        simpleText: 'B.Sc. Nursing or GNM diploma',
        remedyText: 'Complete B.Sc. Nursing or GNM.',
      },
      {
        externalRef: 'GUJ-GMC-NURSE-2026',
        requirementKind: 'registration',
        operator: 'exists',
        isMandatory: true,
        rawText: 'Registration with Gujarat Nursing Council (GNC)',
        simpleText: 'Gujarat Nursing Council (GNC) registration',
        remedyText: 'Register with Gujarat Nursing Council.',
      },

      // Madhya Pradesh
      {
        externalRef: 'MP-NHM-NURSE-2026',
        requirementKind: 'qualification',
        operator: 'in',
        valueText: ['bsc_nursing', 'gnm', 'post_basic', 'msc'],
        isMandatory: true,
        rawText: 'Passed B.Sc. Nursing or GNM from a recognized university/board',
        simpleText: 'B.Sc. Nursing or GNM diploma',
        remedyText: 'Complete B.Sc. Nursing or GNM.',
      },
      {
        externalRef: 'MP-NHM-NURSE-2026',
        requirementKind: 'registration',
        operator: 'exists',
        isMandatory: true,
        rawText: 'Valid Live Registration in Madhya Pradesh Nurses Registration Council (MPNRC)',
        simpleText: 'Madhya Pradesh Nurses Registration Council registration',
        remedyText: 'Renew or register with MPNRC Bhopal.',
      },
    ],
  };
}
