import { runScraperPipeline } from './pipeline';
import * as fs from 'fs';
import * as path from 'path';

async function main() {
  const result = await runScraperPipeline();

  // Separate jobs and exams for mock-data.ts
  const jobs = result.opportunities
    .filter((o) => o.opportunityType === 'job')
    .map((j) => ({
      id: `job-${j.externalRef.toLowerCase()}`,
      professionId: 'prof-nursing',
      professionCode: 'nursing',
      slug: j.slug,
      title: j.title,
      employer: j.organisation,
      type: j.jobType || 'government',
      locationState: j.locationState,
      locationCity: j.locationCity,
      role: j.role,
      qualification: j.qualificationSummary,
      experienceMin: j.experienceMinYears ?? undefined,
      experienceMax: j.experienceMaxYears ?? undefined,
      salaryMin: j.salaryMin ?? undefined,
      salaryMax: j.salaryMax ?? undefined,
      salaryRaw: j.salaryRaw ?? undefined,
      vacancyCount: j.vacancyCount ?? undefined,
      applicationDeadline: j.applicationDeadline ? `${j.applicationDeadline}T23:59:59Z` : undefined,
      status: j.status,
      officialNotificationUrl: j.officialNotificationUrl ?? undefined,
      applicationUrl: j.applicationUrl ?? undefined,
      source: j.sourceName,
      sourceType: j.sourceType,
      descriptionSimple: j.descriptionSimple,
      lastVerified: `${j.lastVerifiedAt}T10:00:00Z`,
    }));

  const exams = result.opportunities
    .filter((o) => o.opportunityType === 'exam')
    .map((e) => ({
      id: `exam-${e.externalRef.toLowerCase()}`,
      professionId: 'prof-nursing',
      professionCode: 'nursing',
      slug: e.slug,
      name: e.title,
      organisation: e.organisation,
      qualification: e.qualificationSummary,
      vacancies: e.vacancyCount ?? undefined,
      applicationStart: e.applicationStart ? `${e.applicationStart}T00:00:00Z` : undefined,
      applicationDeadline: e.applicationDeadline ? `${e.applicationDeadline}T23:59:59Z` : undefined,
      examDate: e.examDate ? `${e.examDate}T09:00:00Z` : undefined,
      admitCardDate: e.admitCardDate ? `${e.admitCardDate}T00:00:00Z` : undefined,
      status: e.status,
      officialNotificationUrl: e.officialNotificationUrl ?? undefined,
      applicationUrl: e.applicationUrl ?? undefined,
      source: e.sourceName,
      sourceType: e.sourceType,
      descriptionSimple: e.descriptionSimple,
      lastVerified: `${e.lastVerifiedAt}T10:00:00Z`,
    }));

  const requirements = result.requirements.map((r, idx) => {
    const opp = result.opportunities.find((o) => o.externalRef === r.externalRef);
    const isJob = opp?.opportunityType === 'job';
    const isExam = opp?.opportunityType === 'exam';

    return {
      id: `req-${idx + 1}`,
      jobId: isJob ? `job-${r.externalRef.toLowerCase()}` : undefined,
      examId: isExam ? `exam-${r.externalRef.toLowerCase()}` : undefined,
      kind: r.requirementKind,
      operator: r.operator ?? undefined,
      valueNumeric: r.valueNumeric ?? undefined,
      valueText: Array.isArray(r.valueText) ? r.valueText : r.valueText ? r.valueText.split('|') : undefined,
      isMandatory: r.isMandatory,
      orGroup: r.orGroup ?? undefined,
      rawText: r.rawText,
      simpleText: r.simpleText ?? undefined,
      remedyText: r.remedyText ?? undefined,
    };
  });

  const mockDataContent = `// Auto-generated by Scraper Pipeline on ${new Date().toISOString()}

export interface MockJob {
  id: string;
  professionId: string;
  professionCode: string;
  slug: string;
  title: string;
  employer: string;
  type: 'government' | 'private';
  locationState?: string;
  locationCity?: string;
  role?: string;
  qualification?: string;
  experienceMin?: number;
  experienceMax?: number;
  salaryMin?: number;
  salaryMax?: number;
  salaryRaw?: string;
  vacancyCount?: number;
  applicationDeadline?: string;
  status: 'open' | 'upcoming' | 'closed' | 'expired';
  officialNotificationUrl?: string;
  applicationUrl?: string;
  source: string;
  sourceType: 'official' | 'verified_secondary' | 'other';
  descriptionSimple: string;
  lastVerified: string;
}

export interface MockExam {
  id: string;
  professionId: string;
  professionCode: string;
  slug: string;
  name: string;
  organisation: string;
  qualification?: string;
  eligibilitySimple?: string;
  vacancies?: number;
  applicationStart?: string;
  applicationDeadline?: string;
  examDate?: string;
  admitCardDate?: string;
  admitCardUrl?: string;
  syllabusUrl?: string;
  resultDate?: string;
  cutoff?: string;
  status: 'open' | 'upcoming' | 'closed' | 'expired';
  officialNotificationUrl?: string;
  applicationUrl?: string;
  source: string;
  sourceType: 'official' | 'verified_secondary' | 'other';
  descriptionSimple: string;
  lastVerified: string;
}

export interface MockRequirement {
  id: string;
  jobId?: string;
  examId?: string;
  kind: 'qualification' | 'experience' | 'registration' | 'age' | 'language' | 'document' | 'other';
  operator?: string;
  valueNumeric?: number;
  valueText?: string[];
  isMandatory: boolean;
  orGroup?: string;
  rawText: string;
  simpleText?: string;
  remedyText?: string;
}

export const INITIAL_JOBS: MockJob[] = ${JSON.stringify(jobs, null, 2)};

export const INITIAL_EXAMS: MockExam[] = ${JSON.stringify(exams, null, 2)};

export const INITIAL_REQUIREMENTS: MockRequirement[] = ${JSON.stringify(requirements, null, 2)};
`;

  const mockDataPath = path.join(process.cwd(), 'src', 'lib', 'mock-data.ts');
  fs.writeFileSync(mockDataPath, mockDataContent, 'utf-8');

  console.log(`🎉 Market Seeding Complete!`);
  console.log(`   - Generated ${jobs.length} Real Jobs across States`);
  console.log(`   - Generated ${exams.length} Real National/State Exams`);
  console.log(`   - Generated ${requirements.length} Structured Requirements`);
  console.log(`   - Output updated at: src/lib/mock-data.ts`);
}

main().catch(console.error);
