import * as React from 'react';
export type IconName =
  | "AlarmClock"
  | "AlertCircle"
  | "AnnotationQuestion"
  | "ArrowLeft"
  | "ArrowNarrowRight"
  | "ArrowRight"
  | "ArrowSquareLeft"
  | "ArrowUp"
  | "Bank"
  | "BookOpen01"
  | "Calendar"
  | "Camera02"
  | "Check"
  | "CheckCircle"
  | "CheckCircleBroken"
  | "ChevronDown"
  | "ChevronLeft"
  | "ChevronRight"
  | "ChevronUp"
  | "Clock"
  | "ClockRewind"
  | "ClockStopwatch"
  | "Copy01"
  | "CreditCard02"
  | "CurrencyDollarCircle"
  | "Database03"
  | "Diamond01"
  | "Expand03"
  | "File06"
  | "FileSearch01"
  | "FileSearch02"
  | "Gift01"
  | "Headphones02"
  | "HelpCircle"
  | "Home03"
  | "HomeLine"
  | "Hourglass03"
  | "Image03"
  | "ImageUserCheck"
  | "InfoCircle"
  | "Lightbulb05"
  | "LinkExternal02"
  | "Lock01"
  | "LockUnlocked03"
  | "Mail01"
  | "Menu01"
  | "MessageChatCircle"
  | "MessageQuestionCircle"
  | "Microphone01"
  | "MicrophoneOff01"
  | "Passport"
  | "PhoneCall01"
  | "Plane"
  | "PlusCircle"
  | "Recording02"
  | "RefreshCcw01"
  | "ReverseLeft"
  | "Route"
  | "SearchLg"
  | "ShieldTick"
  | "Shuffle01"
  | "ThumbsUp"
  | "Trophy01"
  | "Upload01"
  | "User01"
  | "UserCheck02"
  | "VolumeMax"
  | "Wallet02"
  | "XClose";
/**
 * Intentional addition: one wrapper over the 69 glyphs extracted from the
 * .fig, so consumers do not import 69 separate components. No new artwork.
 */
export interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: IconName;
  size?: number | string;
}
export declare const Icon: React.FC<IconProps>;
export default Icon;
